file_format: "1"
id: pkb
name: The pkb
type: shield
url: https://github.com/pakky94/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - pkb_left
  - pkb_right
  - pkb_case